fun main(){
    print("Student Enrollment no:")
    var s1 = readLine()!!.toLong()
    print("Student Name:")
    var s2 = readLine()!!.toString()
    print("Student Branch:")
    var s3 = readLine()!!.toString()
    print("Student Class:")
    var s4 = readLine()!!.toString()
    print("Student Batch:")
    var s5 = readLine()!!.toString()
    print("Student College Name:")
    var s6 = readLine()!!.toString()
    print("Student University Name:")
    var s7 = readLine()!!.toString()
    print("Student Age:")
    var s8 = readLine()!!.toInt()

    println("Enrollment No: = $s1")
    println("Name: = $s2")
    println("Branch: = $s3")
    println("Class: = $s4")
    println("Batch: = $s5")
    println("College Name: = $s6")
    println("University Name: = $s7")
    println("Age: = $s8")
}
